version: '3.9'

services:
  redis-server:
   image: redis:6.2-alpine
   ports:
     - 6379:6379 
  mysql-server:
   image: mysql:8.0.31
   ports:
     - 3306:3306
   environment:
    MYSQL_ROOT_PASSWORD: whatever
  dockerise-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - 5001:5001



      
